#### Import numpy package

In [1]:
import numpy as np

###### Create two 3x3 matrices

In [2]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[7,8,9],[1,2,3],[4,5,6]])

###### Get the shape of the matrix

In [3]:
print ("Matrix A's Shape : ",A.shape)
print ("Matrix B's Shape : ",B.shape)

Matrix A's Shape :  (3, 3)
Matrix B's Shape :  (3, 3)


#### Basic Operations

Verify *commutative property*.

##### Addition

In [4]:
(A+B == B+A).all()

True

In [5]:
A+B

array([[ 8, 10, 12],
       [ 5,  7,  9],
       [11, 13, 15]])

In [6]:
B+A

array([[ 8, 10, 12],
       [ 5,  7,  9],
       [11, 13, 15]])

So, matrixx addition is commutative, $ A + B = B + A $

##### Subtraction

In [7]:
(A-B == B-A).all()

False

In [8]:
A-B

array([[-6, -6, -6],
       [ 3,  3,  3],
       [ 3,  3,  3]])

In [9]:
B-A

array([[ 6,  6,  6],
       [-3, -3, -3],
       [-3, -3, -3]])

So, matrixx subtraction is **NOT** commutative, $ A - B \neq B - A $

##### Multiplication

In [10]:
((A.dot(B)) == (B.dot(A))).all()

False

In [11]:
A.dot(B)

array([[ 21,  27,  33],
       [ 57,  72,  87],
       [ 93, 117, 141]])

In [12]:
B.dot(A)

array([[102, 126, 150],
       [ 30,  36,  42],
       [ 66,  81,  96]])

So, can we say matrixx multiplication is always commutative, $ A \times B \neq B \times A $. N

###### Division

In [13]:
(A/B == B/A).all()

False

In [14]:
A/B

array([[0.14285714, 0.25      , 0.33333333],
       [4.        , 2.5       , 2.        ],
       [1.75      , 1.6       , 1.5       ]])

In [15]:
B/A

array([[7.        , 4.        , 3.        ],
       [0.25      , 0.4       , 0.5       ],
       [0.57142857, 0.625     , 0.66666667]])

So, matrixx division is **NOT** commutative, $ {A \over B} \neq {B \over A} $

###### matrixx addition with a scalar is commutative. 

In [16]:
A-2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [17]:
2-A

array([[ 1,  0, -1],
       [-2, -3, -4],
       [-5, -6, -7]])

###### matrixx subtraction with a scalar is NOT commutative. 

In [18]:
(A-2 == 2-A).all()

False

In [19]:
a=np.array([[1,2,3,4],[1,2,3,4]])

In [20]:
a.shape

(2, 4)

$$ repeat \space until \space convergence:  \{ $$
                                        $$ h_\theta = {1 \over 2m} \sum_{j=0}^m (h_\theta x^{(i)}-  y^{(i)})^2 $$

$$ Take $\frac{1}{2}$ cup of sugar, \dots
 
  3\times\sfrac{1}{2}=1\sfrac{1}{2} $$