#### Import numpy package

In [10]:
import numpy as np

###### Create three 3x3 matrices

In [11]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[7,8,9],[1,2,3],[4,5,6]])
B=np.array([[4,5,6],[7,8,9],[1,2,3]])

###### Get the shape of the matrix

In [12]:
print ("Matrix A's Shape : ",A.shape)
print ("Matrix B's Shape : ",B.shape)
print ("Matrix C's Shape : ",C.shape)

Matrix A's Shape :  (3, 3)
Matrix B's Shape :  (3, 3)
Matrix C's Shape :  (3, 3)


#### Basic Operations

Verify *Associative property*.

##### Addition

In [31]:
(((A+B)+C) == (A+(B+C))).all()

True

In [32]:
(A+B)+C

array([[ 9, 12, 15],
       [18, 21, 24],
       [ 9, 12, 15]])

In [33]:
A+(B+C)

array([[ 9, 12, 15],
       [18, 21, 24],
       [ 9, 12, 15]])

So, matrixx addition is associative, $ (A + B) + C = A + (B + C) $

##### Subtraction

In [34]:
(((A-B)-C) == (A-(B-C))).all()

False

In [17]:
(A-B)-C

array([[-3, -3, -3],
       [-3, -3, -3],
       [ 6,  6,  6]])

In [35]:
A-(B-C)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

So, matrixx subtraction is **NOT** associative, $ (A - B) - C = A - (B - C) $